# .air.toml 配置文件
root = "."
tmp_dir = "tmp"

[build]
# 构建命令
cmd = "go build -o ./tmp/main ./cmd/server"
# 二进制文件路径
bin = "./tmp/main"
# 监视的文件扩展名
include_ext = ["go", "tpl", "tmpl", "html"]
# 排除的目录
exclude_dir = ["assets", "tmp", "vendor", ".git", "node_modules"]
# 排除的文件
exclude_file = []
# 排除的正则表达式
exclude_regex = ["_test.go"]
# 排除的未更改的文件
exclude_unchanged = true
# 监视目录的轮询间隔（毫秒）
poll = 1000
# 在构建之前运行的命令
full_bin = ""
# 构建延迟（毫秒）
delay = 1000
# 在杀死进程之前发送中断信号
kill_delay = 500
# 在启动之前运行的命令
pre_cmd = []
# 在启动之后运行的命令
post_cmd = []
# 在退出之前运行的命令
stop_cmd = []
# 发送中断信号而不是终止信号
send_interrupt = false
# 在启动之前杀死进程
kill_signal = "SIGTERM"

[log]
# 显示日志时间
time = true
# 显示文件名
file = false

[color]
# 主要颜色
main = "magenta"
# 监视器颜色
watcher = "cyan"
# 构建颜色
build = "yellow"
# 运行颜色
runner = "green"
# 应用程序颜色
app = "white"

[misc]
# 清除屏幕
clean_on_exit = true
